services:
  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=volkovlabs-variable-panel
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-timeseries-panel
      - ./provisioning:/etc/grafana/provisioning

  timescale:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./timescale:/docker-entrypoint-initdb.d

  server:
    build:
      context: ./timescale
    ports:
      - 3001:3001/tcp
    depends_on:
      - timescale
    environment:
      WAIT_HOSTS: timescale:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: timescale
